#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       not POSIX-compliant, you can set SHELL to point to a POSIX-compliant
#       shell, e.g. "/bin/bash".
#   (2) The script needs to be executable. Use chmod +x to make it executable.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}    # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum number of file descriptors if possible.
max_fds=$(ulimit -n -H) 2>/dev/null || max_fds=4096
if [ "$max_fds" != "unlimited" ] && [ "$(ulimit -n)" -lt "$max_fds" ]; then
    ulimit -n $max_fds 2>/dev/null || true
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
#     and any embedded shellness will be escaped.
#   * For simplicity, we assume a single argument value for all variables, and we take the first argument for all variables.

set -- \
    "-Dorg.gradle.appname=${APP_BASE_NAME}" \
    -classpath \
    "\"${APP_HOME}${SEP}gradle${SEP}wrapper${SEP}gradle-wrapper.jar\"" \
    org.gradle.wrapper.GradleWrapperMain

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1; then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we also remove the ' and " quoting, but we use eval to do that.
# In bash, the last eval is necessary because parsing of args stops at the
# first meta-character (space, tab, ;, &, |, etc.) and all tokens containing
# meta-characters are parsed as a single argument.
#
# In sh, there is no meta-character handling and eval works as expected.

# Parse all arguments using eval. This is the safest way to parse arguments in POSIX sh, because of word splitting and quoting.
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "$@"

# Use eval to actually execute the command, using the fully composed command line for java.
eval exec "$JAVA_CMD" "$@"
