#!/bin/sh
##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
set -- \
    "-Dorg.gradle.appname=${APP_BASE_NAME}" \
    -classpath \
    "\"${APP_HOME}/gradle/wrapper/gradle-wrapper.jar\"" \
    org.gradle.wrapper.GradleWrapperMain "$@"

# Use eval to actually execute the command.
eval exec "$JAVA_CMD" "$@"
